### ISSUE TITLE
@SandCodes first issue assignment. 

### ISSUE THREAD

**Issue by justinshortio** [shortorigin/purpledurple#2]
#### Instructions
1. Visit the following link and gain an overview of the resources you have available to you. [GitHub Guides](https://guides.github.com/)
2. After reviewing the guides, on your own figure out how to mark the issue in progress.
3. Review the project board for purpledurple. [Projects](https://github.com/shortorigin/purpledurple/projects)
4. Finally, after you've explored around the interface, close the issue. 

##### Good Luck!

**Comment by SandCodes** [comment]
im done
